name: Fuzz
on:
  push:
    branches-ignore:
      - release
      - release-v*
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -trimpath
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.4

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: fuzz-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            fuzz-go-

      - name: Build Go
        run: go install golang.org/dl/gotip@latest && gotip download dev.fuzz

      # TODO(tie) upload diff as artifact on failure
      - name: Run tests
        run: gotip test -v -run=^Fuzz -test.fuzztime=5m -test.fuzz=. ./...
